title: VAPE IT!
author: Macey
email: your-email@domain.com
description: > vaping is way better then smoking 
theres making e liquid coils many things to do and 
most important it healthly then smoking.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
